name = "mateusfccp.me"
license = "MIT"
licenselink = "https://github.com/mateusfccp/mateusfccp.me-hugo/blob/master/LICENSE.md"
description = "Pretty basic theme for Hugo that covers my site current needs."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.54

[author]
  name = "Mateus Felipe Cordeiro Caetano Pinto"
  homepage = "http://mateusfccp.me"
  twitter = "https://twitter.com/mateusfccp"

[original]
  name = "hello-friend-ng"
  homepage = "ttps://github.com/rhazdon/hugo-theme-hello-friend-ng"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
